- name: Run using a project directory
  hosts: docker
  gather_facts: no
  tasks:
    - name: Running docker-compose down
      docker_compose:
        project_src: /root/docker-ansible-build
        state: absent
      #command: docker-compose down
    
    - name: Running docker-compose up
      docker_compose:
        project_src: /root/docker-ansible-build
      register: output

    - debug:
        var: output