{
 "title": "Node dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without (cpu)(irate (node_cpu_seconds_total{job=\"node-exporter\",instance=\"node-exporter:9100\", mode!=\"idle\"}[1m]))",
     "legendFormat": "{{mode}}"
    },
    {}
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\"} - node_memory_MemFree_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\"} - node_memory_Cached_bytes{job=\"node-exporter\",instance=\"node-exporter:9100\"} - node_memory_Buffers_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"node-exporter\",instance=\"node-exporter:9100\",device!~\"/dev/loop.*\", device!~\"tmpfs|nsfs\", device!=\"gvfsd-fuse\"} - node_filesystem_avail_bytes{job=\"node-exporter\",instance=\"node-exporter:9100\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_filesystem_avail_bytes{job=\"node-exporter\",instance=\"node-exporter:9100\",device!~\"/dev/loop.*\",device!~\"tmpfs|nsfs\",device!=\"gvfsd-fuse\"}",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node-exporter\",instance=\"node-exporter:9100\"}[5m])",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node-exporter\",instance=\"node-exporter:9100\"}[5m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  }
 ]
}